### ISSUE TITLE
Test Plan Documents

### ISSUE THREAD

**Issue by rahutchinson** [rahutchinson/InvestiMapp#31]

**Comment by rahutchinson** [comment]
how is this coming?

**Comment by rahutchinson** [comment]
https://www.cypress.io/ I would like to use this

**Comment by rahutchinson** [comment]
for reference
 http://www.softwaretestinghelp.com/wp-content/qa/uploads/2014/02/Live_Project_Test_Plan_SoftwareTestingHelp.pdf

**Comment by WesScott** [comment]
Going well, I understood the testing pretty well. And I’ll be sure to incorporate that.
