### ISSUE TITLE
Create Software Requirements Specification Document

### ISSUE THREAD

**Issue by WesScott** [rahutchinson/InvestiMapp#5]

**Comment by WesScott** [comment]
According to the "Detail of the Project" document on Blackboard, these are the same document, so I'm deleting the UCM document task, and updated this title accordingly.

**Comment by rahutchinson** [comment]
@WesScott @thabear @DarrelDonald @hujiku9 @jaymac22 

I'd like you guys to review this. One to get a better understanding of the project and another to review the work.

**Comment by rahutchinson** [comment]
finished
